const categoryConfig = {
    "Đồ điện tử": {
        "Điện thoại": {
            condition: ["Mới", "Đã sử dụng (chưa sửa chữa)", "Đã sử dụng (qua sửa chữa)"],
            brand: [
                "Acer",
                "Asus",
                "Alienware",
                "Apple",
                "HP",
                "Lenovo",
                "MSI",
                "Samsung",
                "Dell",
                "Gigabyte",
                "Microsoft",
                "Razer",
                "Huawei",
                "LG",
                "Nokia",
                "Masstel",
                "Vsmart",
                "Xiaomi",
                "Realme",
                "Oppo",
                "Vivo",
                "OnePlus",
                "Infinix",
                "Tecno",
                "Itel",
                "BlackBerry",
                "Energizer",
                "Mobell",
                "Philips",
                "Asanzo",
                "HTC",
                "Khác",
            ],
            capacity: [
                "< 8GB",
                "8 GB",
                "16 GB",
                "32 GB",
                "64 GB",
                "128 GB",
                "256 GB",
                "512 GB",
                "1 TB",
                "2 TB",
                "> 2 TB",
            ],
            warranty: [
                "Hết bảo hành",
                "1 tháng",
                "2 tháng",
                "3 tháng",
                "4-6 tháng",
                "7-12 tháng",
                ">12 tháng",
                "Còn bảo hành",
            ],
            origin: null,
            isFree: false,
            price: null,
        },
        "Máy tính bảng": {
            condition: ["Mới", "Đã sử dụng (chưa sửa chữa)", "Đã sử dụng (qua sửa chữa)"],
            brand: [
                "Acer",
                "Apple",
                "Asus",
                "HUAWEI",
                "Lenovo",
                "Masstel",
                "Mobell",
                "Oppo",
                "Samsung",
                "Xiaomi",
                "Hãng khác",
            ],
            capacity: [
                "< 8GB",
                "8 GB",
                "16 GB",
                "32 GB",
                "64 GB",
                "128 GB",
                "256 GB",
                "512 GB",
                "1 TB",
                "2 TB",
                "> 2 TB",
            ],
            warranty: [
                "Chính sách bảo hành",
                "Hết bảo hành",
                "1 tháng",
                "2 tháng",
                "3 tháng",
                "4-6 tháng",
                "7-12 tháng",
                ">12 tháng",
                "Còn bảo hành",
            ],
            version: ["Quốc tế", "Quốc tế (khóa mạng)", "Chính hãng", "Xách tay"],
            screenSize: [
                "< 7 inch",
                "7 - 7.9 inch",
                "8 - 8.9 inch",
                "9 - 9.9 inch",
                "10 - 10.9 inch",
                "> 10.9 inch",
            ],
            origin: null,
            isFree: false,
            price: null,
        },
        Laptop: {
            condition: ["Mới", "Đã sử dụng (chưa sửa chữa)", "Đã sử dụng (qua sửa chữa)"],
            brand: [
                "Acer",
                "Apple",
                "Asus",
                "Dell",
                "Gigabyte",
                "Honor",
                "HP",
                "Lenovo",
                "LG",
                "Microsoft",
                "MSI",
                "Panasonic",
                "Razer",
                "Samsung",
                "Sony",
                "Toshiba",
                "Hãng khác",
            ],
            storage: [
                "< 8GB",
                "8 GB",
                "16 GB",
                "32 GB",
                "64 GB",
                "128 GB",
                "256 GB",
                "512 GB",
                "1 TB",
                "2 TB",
                "> 2 TB",
            ],
            warranty: [
                "Chính sách bảo hành",
                "Hết bảo hành",
                "1 tháng",
                "2 tháng",
                "3 tháng",
                "4-6 tháng",
                "7-12 tháng",
                ">12 tháng",
                "Còn bảo hành",
            ],
            cpu: [
                "AMD",
                "Athlon",
                "Intel Atom",
                "Intel Celeron",
                "Intel Core 2 Duo",
                "Intel Core 2 Quad",
                "Intel Core i3",
                "Intel Core i5",
                "Intel Core i7",
                "Intel Core i9",
                "Intel Pentium",
                "Intel Quark",
                "Intel Xeon",
                "Ryzen 3",
                "Ryzen 5",
                "Ryzen 7",
                "Ryzen 9",
                "Khác",
            ],
            ram: ["< 1 GB", "1 GB", "2 GB", "4 GB", "6 GB", "8 GB", "16 GB", "32 GB", "> 32GB"],
            screenSize: [
                "< 9 inch",
                "9 - 10.9 inch",
                "11 - 12.9 inch",
                "13 - 14.9 inch",
                "15 - 16.9 inch",
                "17 - 18.9 inch",
                "19 - 20.9 inch",
                ">= 21 inch",
            ],
            origin: null,
            isFree: false,
            price: null,
        },
        "Máy ảnh/Máy quay": {
            condition: ["Mới", "Đã sử dụng (chưa sửa chữa)", "Đã sử dụng (qua sửa chữa)"],
            deviceType: ["Máy ảnh", "Máy quay", "Ống kính", "Khác"],
            warranty: [
                "Chính sách bảo hành",
                "Hết bảo hành",
                "1 tháng",
                "2 tháng",
                "3 tháng",
                "4-6 tháng",
                "7-12 tháng",
                ">12 tháng",
                "Còn bảo hành",
            ],
            origin: null,
            isFree: false,
            price: null,
        },
        "Tivi/Âm thanh": {
            condition: ["Mới", "Đã sử dụng (chưa sửa chữa)", "Đã sử dụng (qua sửa chữa)"],
            deviceType: ["Tivi", "Loa", "Amply", "Tai nghe", "Micro", "Karaoke"],
            warranty: [
                "Chính sách bảo hành",
                "Hết bảo hành",
                "1 tháng",
                "2 tháng",
                "3 tháng",
                "4-6 tháng",
                "7-12 tháng",
                ">12 tháng",
                "Còn bảo hành",
            ],
            origin: null,
            isFree: false,
            price: null,
        },
        "Thiết bị đeo thông minh": {
            condition: ["Mới", "Đã sử dụng (chưa sửa chữa)", "Đã sử dụng (qua sửa chữa)"],
            deviceType: ["Đồng hồ thông minh", "Vòng tay thông minh", "Khác"],
            brand: ["Apple", "Fitbit", "Garmin", "Huawei", "Misfit", "Samsung", "Xiaomi", "Khác"],
            warranty: [
                "Chính sách bảo hành",
                "Hết bảo hành",
                "1 tháng",
                "2 tháng",
                "3 tháng",
                "4-6 tháng",
                "7-12 tháng",
                ">12 tháng",
                "Còn bảo hành",
            ],
            origin: null,
            isFree: false,
            price: null,
        },
        // Add other sub-categories and main categories as needed
    },
    // Other main categories like "Đồ ăn, thực phẩm và các loại khác" would go here...
    "Đồ ăn, thực phẩm và các loại khác": {
        condition: ["Đã sử dụng", "Mới"],
        foodType: [
            "Bánh kẹo, đồ ăn vặt",
            "Bơ, sữa, trứng",
            "Đồ khô, mắm, gia vị",
            "Đồ uống - giải khát",
            "Rau, củ, trái cây",
            "Thịt",
            "Thực phẩm chế biến sẵn",
            "Hải sản",
            "Thực phẩm khác",
        ],
        origin: null,
        isFree: false,
        price: null,
    },
    
};

export default categoryConfig;
