on:
    push:
        branches: ["main"]
  
jobs:
    scs-fe-build:
      name: Build source code to Docker image
      runs-on: ubuntu-22.04 
      env:
        DOCKER_USERNAME: ${{secrets.DB_USERNAME}}
      steps:
        - name: Checkout Develop
          uses: actions/checkout@v3
  
        - name: DockerHub Login
          uses: docker/login-action@v3.1.0
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_TOKEN}}
  
        - name: Build Image And Push
          run: docker compose build scs-fe && docker compose push scs-fe
    
    staging-fe-deploy:
      name: Deploy Staging FE Admin To Google Service Server For Testing
      runs-on: arisa-deploy
      needs: scs-fe-build
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Stop SCS FE
        run: docker compose -f docker-compose.prod.yaml -p secondchanceshop-api down scs-fe --rmi all -v
        continue-on-error: true
      - name: Deploy SCS FE
        run: docker compose -f docker-compose.prod.yaml -p secondchanceshop-api up -d scs-fe